### PR TITLE
fix(sdk): Workaround to set the media_keys on the MediaBrowser

### LINKED ISSUE #5587: [CLI]: Bug - The media_keys attribute on MediaBrowser for reports doesn't work
### Describe the bug

Defining a Panel Grid on a report as shown below, the media_keys attribute doesn't work, when it's save on the UI the selection on the media key that shown is random, in the example I put, I tried to shown "plt_test_calibration" but instead on the UI it shows a random media (example on the screenshot).

```python
calibration = wr.PanelGrid(
        runsets=[
            wr.Runset(
                project=project_name,
                entity=entity,
                name="Run set",
                filters={'name': {'$in': [run_id]}},
                order=["-CreatedTimestamp"],
            )
        ],
        panels=[
            wr.MediaBrowser(layout={"x": 0, "y": 10, "w": 24, "h": 10}, 
                            media_keys="plt_test_calibration")
        ],
    )
```
Comparing with a report that I load from a url, the attribute on the `spec.config` that defines which media key to use is `mediaKeys` not `media_keys` as you guys have on the code.

https://github.com/wandb/wandb/blob/main/wandb/apis/reports/_panels.py#L653 

I've code a workaround for this that also puts the `spec.config.media_keys` attribute because if is not defined the UI of the report completely crash

### Additional Files

_No response_

### Environment

WandB version: 0.15.3

OS: Ubuntu 22.04

Python version: 3.10

Versions of relevant libraries:

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by juansebashr**
Fixes
-----
Fixes #5587

Description
-----------
Adds a workaround on the MediaBrowser() class for the reports so the `media_keys` attribute of the class define the `mediaKeys` attribute on the `spec.config`, but also maintaining the `spec.config.media_keys` attribute so the report doesn't crash 

(I know is not the most elegant solution but it works while you guys can fix it also in the UI side)

Testing
-------
On multiple tests generating reports and evaluating the results

Checklist
-------
- [x] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [x] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#conventional-commits)

### <samp>🤖 Generated by Copilot at 17df61b</samp>

> _No more errors in the frontend_
> _`MediaBrowser` panel is transcendent_
> _Multiple keys for the media lords_
> _`media_key_placeholder` for the hordes_

### CODE REVIEW

**Comment by dmitryduev** [comment]
@andrewtruong could you please take a look?

**Comment by andrewtruong** [comment]
Hey, sorry it took a while to look at this!

It seems like you have both `mediaKeys` and `media_keys` -- did you need both of them?

**Comment by juansebashr** [comment]
@andrewtruong Yeah, because for some reason if I don't have both of them the UI crash

**Comment by andrewtruong** [comment]
Closing as I think this was addressed in another PR that I can't find atm.  We're also releasing v2 of the Report API soon.  If the issue shows up again there, please let us know

**Pull request closed without merging**
