### PR TITLE
style(sdk): make type annotations more easily navigable in my IDE

### PR DESCRIPTION
**Pull request by speezepearson**
Description
-----------

My IDE has trouble following some of our fully-qualified-type-name type annotations, even though Mypy understands them. I'm not sure why there's a mismatch there, but empirically, importing the relevant modules solves it:

- Before:

    Screen Shot 2022-07-28 at 16 17 33

    If I "Go to definition" on those names, nothing happens.

- After:

    Screen Shot 2022-07-28 at 16 17 44

    If I "Go to definition" on those names, I go to the right place!

Testing
-------
n/a; all changes are in `if TYPE_CHECKING:`

### CODE REVIEW

**Review by kptkin — APPROVED** [review]
🔥

**Comment by dmitryduev** [comment]
@speezepearson do you want this in the upcoming release?
In any case, could you please fix the conflicts and merge?

**Comment by speezepearson** [comment]
@dmitryduev Thanks for the prod! No need for this to be in the release. I've fixed the conflicts (we'll see if CI agrees), and it should auto-merge as soon as the checks (incl. mergefreeze) pass.

**Comment by dmitryduev** [comment]
thanks @speezepearson, however it looks like there are more conflicts/linting issues :( sry about that :(

**Pull request merged**
