### PR TITLE
fix(integrations): fix Keras WandbCallback in MirroredStrategy raising an error

### LINKED ISSUE #4113: [CLI]: v0.13.1 Training results in IndexError: pop when using WandbCallback
### Describe the bug

Training starts, but never completes due to the bug.
At the end of the training phase I get the following error:
```shell
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-f5faf23168b9> in <module>
      1 results = model.fit(z_train, y_train, batch_size=config.batch_size, epochs=config.epochs, callbacks=callbacks,\
----> 2                     validation_data=(z_test, y_test))

~/.local/lib/python3.6/site-packages/wandb/integration/keras/keras.py in new_v2(*args, **kwargs)
    171             for cbk in cbks:
    172                 set_wandb_attrs(cbk, val_data)
--> 173         return old_v2(*args, **kwargs)
    174 
    175     training_arrays.orig_fit_loop = old_arrays

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1144         del self._eval_data_handler
   1145       callbacks.on_train_end(logs=training_logs)
-> 1146       return self.history
   1147 
   1148   def test_step(self, data):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py in __exit__(self, exception_type, exception_value, traceback)
    425                          "tf.distribute.set_strategy() out of `with` scope."),
    426             e)
--> 427     _pop_per_thread_mode()
    428 
    429 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribution_strategy_context.py in _pop_per_thread_mode()
     63 
     64 def _pop_per_thread_mode():
---> 65   ops.get_default_graph()._distribution_strategy_stack.pop(-1)  # pylint: disable=protected-access
     66 
     67 

IndexError: pop from empty list
```
When I disable WandbCallback() everything works fine.
I use 2 GPUs on single machine via MirroredStrategy on tensorflow.

### Additional Files

_No response_

### Environment

WandB version: 0.13.1

OS: Ubuntu 18.04.5 LTS

Python version: 3.6.9

Versions of relevant libraries:
tensorflow v2.3.1+nv

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ayulockin**
Fixes [WB-10916](https://wandb.atlassian.net/browse/WB-10916)

Description
-----------
This PR fixes #4113. 

Why remove `tf.compat.v1.reset_default_graph()`?

- From the TF [documentation](https://www.tensorflow.org/api_docs/python/tf/compat/v1/reset_default_graph), "reset_default_graph does not work with either eager execution or [tf.function](https://www.tensorflow.org/api_docs/python/tf/function), and you should not invoke it directly." The `real_model = tf.function(self.model).get_concrete_function(inputs)` is a `tf.function` and thus reseting graph doesn't work anyway.
- I compared the graph logged and visualized on TensorBoard and they are same - [with reset_default_graph](https://wandb.ai/ayut/keras/runs/yr6f1ul4/tensorboard?workspace=user-ayut) and [without](https://wandb.ai/ayut/keras/runs/24gadxcx/tensorboard?workspace=user-ayut).
- I also compared the performance and convergence of the model and its not affected by removing `reset_default_graph`.

Testing
-------
yea tests passing

Checklist
-------
- [x] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [x] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/master/CONTRIBUTING.md#conventional-commits)

### CODE REVIEW

**Comment by kptkin** [comment]
Thanks for the fix! Let's move the flop calculation behind an argument

**Comment by kptkin** [comment]
Overall, make sense! Would mind adding a MirroredStrategy example to our testing (you could add it as another yea test)

**Comment by ayulockin** [comment]
How about we do it as a separate PR? @kptkin

**Comment by kptkin** [comment]
> How about we do it as a separate PR? @kptkin

Why do it in a different PR? 

Just take the repro example and convert it into a script and add simple assertions (you can see many examples in the functional_tests folder).
This was the failing case, so it would be useful to have this example!

**Review by kptkin — APPROVED** [review]
Thanks for the fix and looking into the graph rest issue

**Pull request merged**
