### PR TITLE
feat(sdk, integrations): Autolog Integration for openai major version with detail logging

### LINKED ISSUE #7129: [Feature]: major version of openai client support in autolog
### Description

It seems that major version of openai client can't support in autolog. 
I found lots of issues.

- Can't wrap the openai client constructor using exist PatchAPI class. So PatchAPI can't wrap the openai api for callling run.log.
- OpenAI Trace Table doesn't include the whole information and the structure of data has limited utility, like logging the chat history.
- OpenAIRequestResponseResolver can't handle openai major version(>=1.0.0). All the parsing logic is based on dictionary type, not other property. (e.g., chat_completion.choices[0].message)
- And more...

### Suggested Solution

I'll try to add synchronous open client of major version.

### Alternatives

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by naem1023**
Update integration for openai major version in autolog and utils

Description
-----------

- Fixes #7129 

I found lots of issues in this PR.. 
- Can't wrap the openai major version client constructor using exist PatchAPI class. So PatchAPI can't wrap the openai api for callling run.log.
- OpenAI Trace Table doesn't include the whole information and the structure of data has limited utility, like logging the chat history.
- OpenAIRequestResponseResolver can't handle openai major version(>=1.0.0). All the parsing logic is based on dictionary type, not other property. (e.g., chat_completion.choices[0].message)

So, I resolve the problems.
- [X] Add functions in utils to check the version of openai client
- [X] Add functions in utils to make the simple factory pattern for openai synchronous client
- [X] Update sdk.integration.auto_logging for major version of openai client.
- [x] Update integrations.openai.resolver to handle the response of major version openai client.
- [x] Add integrations.openai.wandb_openai.WandbOpenAIBase which can be used as recursive proxy. It just wrap the class and function. I inspired by [promptlayer's code](https://github.com/MagnivOrg/prompt-layer-library/blob/master/promptlayer/promptlayer.py.) and fix it. I express my gratitude to [promptlayer-library contributors](https://github.com/MagnivOrg).
- [x] Add integrations.openai.resolver.OpenAIRequestResponseResolver for openai major version. It contain improved logging like chat history, openai parameters. 
- [x] Update README.md

Testing
-------
How was this PR tested?

- I integrate wandb autolog in [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) and it works. 
- In tests/pytest_test/unit_test, I found the unit test for autolog and patch api. I will add the new unit test for openai major client version.

### CODE REVIEW

**Comment by ayulockin** [comment]
Hey @naem1023. thank you for working on this PR. 

Note however that we are deprecating this autolog feature in favor of some upcoming product features. This PR adds the deprecation warning: https://github.com/wandb/wandb/pull/7033

**Comment by naem1023** [comment]
@ayulockin 
Ok, so if some new features are implemented and released, autolog isn't work or just deprecated?
If some automatic logging features like autolog will be implemented soon, I want to see the code and contribute.

**Comment by ayulockin** [comment]
@naem1023 as you see the deprecation warning states that: "The OpenAI autolog feature will not be supported for openai version >= 1.0."

we don't plan to support the openai-python > v1.0. sorry for the confusion. 

We will share the code for the new feature as soon as it is ready. :)

**Comment by naem1023** [comment]
Ok I got it. Thanks! I fully support the next plan of wandb.
I have last question. Could I understand that users who is using openai major version(>=1.0.0) currently have no feature available in wandb to view traces, and that support will be provided in the future through a feature other than "autolog"? 

We are always very satisfied with your product. Thank you

**Comment by morganmcg1** [comment]
hey @naem1023 

> Could I understand that users who is using openai major version(>=1.0.0) currently have no feature available in wandb to view traces, and that support will be provided in the future through a feature other than "autolog"?, so the openai major verison sdk doesn't need to be integrated on current wandb sdk.

That is correct

Thanks very much for your contribution nevertheless, I hope you'll enjoy our new LLM tools launching in April!

**Comment by morganmcg1** [comment]
Closing for now

**Pull request closed without merging**
