### PR TITLE
Implement support for IPUs

### PR DESCRIPTION
**Pull request by cameron-martin**
Description
-----------
This adds support for automatically logging various metrics of an IPU, such as temperature, clock speed and utilisation. This is implemented similarly to how TPU support is implemented, where it only runs if the necessary imports are available, in this case a package from our sdk, `gcipuinfo`. This is extracted into it's own class, `IPUProfiler`.

All stats that are returned by gcipuinfo are logged initially, but a lot are static so only a select few are logged on every invocation.

Testing
-------
Some unit tests are added for `IPUProfiler` that mock the interface of the `gcipuinfo` package, as well as some unit tests for the `SystemStats` class to check that it interacts with the IPUProfiler class correctly. Note that no tests actually run anything on the IPU.

Checklist
-------
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if applicable)

### CODE REVIEW

**Comment by vanpelt** [comment]
Thanks @cameron-martin this looks really awesome!  There's a mypy and black formatting error but they should be pretty straightforward to address.  I'll leave the final call to our sdk team but this looks really clean.  We'll also need to add some additional logic to our frontend to ensure these show up in the system metrics panels but it's a simple fix we can handle.

**Review by dmitryduev — APPROVED** [review]
Many thanks for your contribution, @cameron-martin!

**Comment by dmitryduev** [comment]
Out of curiosity, @cameron-martin: are there plans to open-source the `gcipuinfo` library?

**Comment by cameron-martin** [comment]
> Out of curiosity, @cameron-martin: are there plans to open-source the `gcipuinfo` library?

I'm not aware of any such plans. I'll let you know if this situation changes, however.

**Pull request merged**
