### PR TITLE
fix(core): upload output file at the end of the run

### PR DESCRIPTION
**Pull request by kptkin**
Description
-----------

What does the PR do? Include a concise description of the PR contents.

Minor fix to make sure we upload the output log file

- [x] I updated CHANGELOG.md, or it's not applicable

Testing
-------
How was this PR tested?

### CODE REVIEW

**Comment by timoffex** [comment]
Do we need it in the transaction record? It would always get uploaded since the logic is in the sender.

**Comment by kptkin** [comment]
> Do we need it in the transaction record? It would always get uploaded since the logic is in the sender.

wanted to keep to for completeness as well as if the user theoretically uses a different version to sync our transaction log file

**Review by timoffex — APPROVED** [review]
I guess having a record makes sense if we rename the file in a future version.

**Comment by kptkin** [comment]
> I guess having a record makes sense if we rename the file in a future version.

@timoffex i think we should revisit this when we are looking at the sync logic this q, these are all really valid questions!

**Pull request merged**
