### PR TITLE
fix(integrations): make Keras WandbCallback compatible with TF version >= 2.11.0

### PR DESCRIPTION
**Pull request by ayulockin**
Fixes WB-11561

Description
-----------
In [TensorFlow 2.9](https://blog.tensorflow.org/2022/05/whats-new-in-tensorflow-29.html), an experimental version of the new [Keras Optimizer API](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer), `tf.keras.optimizers.experimental` was released. It was done to provide a more unified and expanded catalog of built-in optimizers which can be more easily customized and extended. 

In TensorFlow 2.11, these new optimizers are on by default.

Our Keras `WandbCallback`, `log_gradient` feature creates a `_CustomOptimizer` by subclassing old optimizers API.

This PR creates the `_CustomOptimizer` using the correct parent class. This solves the problem of `log_gradient` feature not working with TF 2.11.0.

Testing
-------
This was manually tested with TF version 2.8.0, 2.9.0, 2.10.0, and 2.11.0. The W&B run pages are linked below:
- [2.8.0](https://wandb.ai/ayut/resume-training/runs/26g4dpb9?workspace=user-ayut)
- [2.9.0](https://wandb.ai/ayut/resume-training/runs/2uene5hp?workspace=user-ayut)
- [2.10.0](https://wandb.ai/ayut/resume-training/runs/j7a52o8x?workspace=user-ayut)
- [2.11.0](https://wandb.ai/ayut/resume-training/runs/3ngk9guu?workspace=user-ayut)

Checklist
-------
- [x] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [x] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/master/CONTRIBUTING.md#conventional-commits)

### CODE REVIEW

**Review by moredatarequired — CHANGES_REQUESTED** [review]
Thank you! Could you also roll back the changes from #4508 to ensure that 2.11 gets tested in CI?

**Review by dmitryduev — APPROVED** [review]
Excellent, thanks a lot for the fix @ayulockin!
+1 on what @moredatarequired requested and then should be good to go in.

**Comment by dmitryduev** [comment]
mypy issue seems unrelated, will look into that separately.

**Comment by dmitryduev** [comment]
@ayulockin @moredatarequired I merged a revert of https://github.com/wandb/wandb/pull/4508 into this branch.

**Review by moredatarequired — APPROVED** [review]

**Pull request merged**
