### PR TITLE
fix(sdk): create_and_run_agent visibility

### PR DESCRIPTION
**Pull request by marijncv**
Description
-----------
- Fixes https://github.com/wandb/wandb/issues/8620

Exposes `create_and_run_agent` function as public API

Testing
-------
How was this PR tested?
n/a

### CODE REVIEW

**Review by TimH98 — APPROVED** [review]
Thank you for the contribution!

**Comment by kptkin** [comment]
@marijncv would you like to update the changelog to include your contribution in the next release notes?

**Comment by marijncv** [comment]
Thanks @kptkin & @TimH98 ! I updated the changelog. My markdown formatter also changed a few unrelated lines, I hope that is ok

**Comment by kptkin** [comment]
> Thanks @kptkin & @TimH98 ! I updated the changelog. My markdown formatter also changed a few unrelated lines, I hope that is ok

Yeah, that's fine! Thanks a lot! I will approve and merge your changes. 
Thanks for the contribution.

**Review by kptkin — APPROVED** [review]

**Pull request merged**
