### PR TITLE
chore(sdk): improve JSONification of dataclasses

### PR DESCRIPTION
**Pull request by HipHoff**
JIRA Ticket
-----------
[WB-14020](https://wandb.atlassian.net/browse/WB-14020)

Description
-----------
This PR parses dataclasses passed in as values of a run's config into dictionaries before the entire config is dumped to JSON and stored in the W&B backend.

Currently, without converting to a dictionary, dataclass values of a run config are rendered in a stringified version that is hard to parse:

image

This also prevents the search bar to be used for attrs of the dataclass.

With this change, each attribute in a dataclass config is rendered out on a separate line, making them easier to parse and search:

image

Testing
-------
Added unit test.

### <samp>🤖 Generated by Copilot at da12309</samp>

> _`Run` with the power of dataclasses_
> _Serialize your config to JSON_
> _Parse and store your values with ease_
> _`_parse_value` is your weapon_

[WB-14020]: https://wandb.atlassian.net/browse/WB-14020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by HipHoff** [comment]
I'd appreciate guidance on where to add a test for this. From skimming the existing tests, the only existing test I can see that touches `run.update` or `json_config` is [this test](https://github.com/wandb/wandb/blob/41febb0f66c13cf78f955479f10279af10e33dd0/tests/pytest_tests/unit_tests_old/test_public_api.py#L125) in unit_tests_old, and I'm not sure if there's a reason we haven't made a similar test in unit_tests.

**Comment by adityachoudhari26** [comment]
🔥🔥🔥

**Review by dmitryduev — APPROVED** [review]

**Pull request merged**
