### PR TITLE
fix(artifacts): fix handling of directory stubs in azure sa

### PR DESCRIPTION
**Pull request by marijncv**
Description
-----------
- Fixes https://github.com/wandb/wandb/issues/7867

This PR adds an extra check in the `azure_handler` to detect a directory stub in an azure storage account with hierarchical namespace enabled. When detected it handles it appropriately:
* Using it as the prefix filter for the rest of the blobs
* Using it to filter our deeper level directory stubs from the tracked references

- [ ] I updated CHANGELOG.md, or it's not applicable

Testing
-------
How was this PR tested?

I added a bit to the system test that covers the `azure_handler` but I was not able to run the test on my local machine with the following error:
```shell
python -m pytest tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
Running tests with wandb version: 0.17.4.dev1
Configuring wandb server...
/Users/marijncv/.pyenv/versions/3.10.13/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 66424 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
docker: Error response from daemon: Head "https://us-central1-docker.pkg.dev/v2/wandb-production/images/local-testcontainer/manifests/master": denied: Unauthenticated request. Unauthenticated requests do not have permission "artifactregistry.repositories.downloadArtifacts" on resource "projects/wandb-production/locations/us-central1/repositories/images" (or it may not exist).
See 'docker run --help'.
Exit: Failed to connect to wandb server
```

Am I supposed to be able to run the test or is this only possible for W&B engineers? Any help is appreciated!

### CODE REVIEW

**Review by amusipatla-wandb — CHANGES_REQUESTED** [review]
Thanks for addressing this bug! Unfortunately, only W&B engineers can run system tests at this time, but it's something we're looking into. I ran the tests myself and we do get an error relating to our mock `BlobProperties` class and the fact that it’s not iterable. I added a few comments about how we can fix that, but otherwise this PR looks good to me. 

After addressing the comments, can you also add the fix info to the changelog?

**Comment by marijncv** [comment]
Thanks for the review @amusipatla-wandb! I've tried to address the comments in the latest commits

**Review by amusipatla-wandb — APPROVED** [review]
looks good to me, thanks for making the changes!

**Comment by marijncv** [comment]
Thanks @amusipatla-wandb! Is there anything I can do to make the PR mergeable?

**Comment by kptkin** [comment]
@amusipatla-wandb @marijncv could you rebase your branch and update the changelog? we already released version 0.17.5 but the changelog doesn't reflect these changes. After rebasing, just move the nice changelog comment to the unreleased section. Thanks

**Comment by kptkin** [comment]
> @amusipatla-wandb @marijncv could you rebase your branch and update the changelog? we already released version 0.17.5 but the changelog doesn't reflect these changes. After rebasing, just move the nice changelog comment to the unreleased section. Thanks

Sorry looks like we have some issue with the changelog, let me quickly address this

**Comment by marijncv** [comment]
Thanks @kptkin! I moved the entry to the unreleased section

**Comment by marijncv** [comment]
@kptkin @amusipatla-wandb can this PR please be merged? Thanks in advance!

**Pull request merged**
