### PR TITLE
fix(public-api): Changed `artifactSequence` to `artifactCollection` in public GQL requests

### PR DESCRIPTION
**Pull request by tssweeney**
https://wandb.atlassian.net/browse/WB-11598

This is some old tech debt from model reg work. ArtifactCollections should always use the `*Collection` style not `*Sequence`.

### CODE REVIEW

**Review by vwrj — CHANGES_REQUESTED** [review]
Looks great. Can we add a quick test to make sure that this successfully pulls from a portfolio?

**Review by vwrj — APPROVED** [review]
Nice.

**Comment by vwrj** [comment]
When this is merged, let's respond to this Github issue here: https://github.com/wandb/wandb/issues/4519. We should
- test that the user's code snippet (pulling `api.artifact_versions` works as a sanity check)
- tell them this will be available in the next SDK release
- create a branch off the currently released version + cherry pick this change on top so that they can be unblocked for their current work until the next release. 

There's 2 users who have responded that are using the API to pull artifact versions for the model registry so there must be more out there who have experienced this issue. So I'd like to unblock them as soon as possible.

**Comment by tssweeney** [comment]
> When this is merged, let's respond to this Github issue here: #4519. We should
> 
> * test that the user's code snippet (pulling `api.artifact_versions` works as a sanity check)
> * tell them this will be available in the next SDK release
> * create a branch off the currently released version + cherry pick this change on top so that they can be unblocked for their current work until the next release.
> 
> There's 2 users who have responded that are using the API to pull artifact versions for the model registry so there must be more out there who have experienced this issue. So I'd like to unblock them as soon as possible.

Great - i tested in notebook and it works:
Screen Shot 2022-11-29 at 8 08 54 AM
Screen Shot 2022-11-29 at 8 11 48 AM

Note: the `Artifact::name` field refers to the "home" artifact sequence, not the collection in question. To fix this we need to add a new GQL edge that lets us go from artifact version to the membership for a collection.

**Comment by tssweeney** [comment]
Created a followup PR to fix the artifact version name issue: https://github.com/wandb/wandb/pull/4547

**Pull request merged**
