### PR TITLE
fix(sdk): Fix custom chart query to work for more broad cases and add alternate constructor to simplify adding charts for tables

### PR DESCRIPTION
**Pull request by andrewtruong**
Fixes [WB-12139](https://wandb.atlassian.net/browse/WB-12139)

Description
-----------
Fixes the `query` param on Custom Charts to support broader use cases (previously it assumed a wrong shape).

Example query param for this custom chart query:
```py
query = {
  "summary": {
    "keys": ["loss", "acc"]
  }
}
```

`runSets`, `id`, and `name` are always present and so they are set by default.

image

Also added an alternate constructor to make supporting tables more obvious.

Previously users could use a table like this:
```
wr.CustomChart(query={"summaryTable": {"tableKey": table_name}})
```

We now add an alternate constructor which is a bit more fluent:
```
wr.CustomChart.from_table(table_name)
```

Testing
-------
TBD

Checklist
-------
- [ ] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [ ] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#conventional-commits)

[WB-12139]: https://wandb.atlassian.net/browse/WB-12139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by vanpelt — DISMISSED** [review]
Nice

**Comment by ludjac** [comment]
Happy to find this PR after debugging for some time. The bug in the CustomChart.query setter is currently blocking for me so would be grateful to see this merged and included in a future release as soon as possible. Anything I can do to assist?

**Comment by andrewtruong** [comment]
@ludjac we should be merging this soon!  Does this branch solve the problem you were running into?

**Review by kptkin — APPROVED** [review]

**Comment by ludjac** [comment]
> @ludjac we should be merging this soon! Does this branch solve the problem you were running into?

Great stuff! Yes it does, thanks 💯

**Pull request merged**
