### PR TITLE
Keras WandbCallback - Remove extra ops for flops calculation

### PR DESCRIPTION
**Pull request by ayulockin**
Fixes WB-NNNN
Fixes #NNNN

Description
-----------
The FLOPs calculation is depending on `convert_variables_to_constants_v2_as_graph` which is not reliable. This PR adds the recommended way of getting graphs, as per this [this section from TensorFlow docs](https://www.tensorflow.org/guide/function#obtaining_graphs).

Testing
-------
How was this PR tested?

Checklist
-------
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if applicable)

### CODE REVIEW

**Review by dmitryduev — CHANGES_REQUESTED** [review]
Thanks a lot @ayulockin! Looks like keras tests broke - could you please look into that and fix?

**Comment by ayulockin** [comment]
Hey @dmitryduev while trying to run the tests locally I am getting, I have started getting this error today: `wandb.errors.CommError: Not implemented in tests/mock_server.py`. I can see that the `mock_server.py`'s path is `tests/utils/mock_server.py`. What should I do to quickly fix it?

**Comment by dmitryduev** [comment]
@ayulockin probably things got out of sync for you? I'd try starting off a fresh branch cut from master and would just port this change there. The failures on the CI look real and suggest that certain tensors sometimes end up on different graphs, and what's worse, in a flaky way. Could you please look into that? I tried quickly repro'ing this locally (couldn't - works on my arm mac), so you may have to rerun the CI jobs with ssh and debug things on the worker. LMK if you assistance with that!

**Comment by dmitryduev** [comment]
@ayulockin do you want to see this change in the upcoming release? 
The test errors look scary enough to call for much more testing + I consider this as a high-risk change as it produces this kind of flake in a very widely-used codepath.

**Comment by ayulockin** [comment]
Hey, @dmitryduev, we can wait for this PR and test it further. The change I made was based on my local testing, and felt would not break the existing tests so severely. I am converting this to a draft for the time.

**Comment by dmitryduev** [comment]
Hey @ayulockin, any updates on this PR?

**Comment by ayulockin** [comment]
Closing this PR as this is not required anymore in favor of #4310.

**Pull request closed without merging**
