### PR TITLE
chore(launch): Return updated runSpec after pushToRunQueue query

### PR DESCRIPTION
**Pull request by gtarpenning**
https://wandb.atlassian.net/browse/WB-11577

Description
-----------
We now update the run spec on the backend based on the default resource configuration for a queue, so we want to reflect that to the user when printing

Testing
-------
new test, should fail for old versions of the backend, but only the test.

### CODE REVIEW

**Comment by gtarpenning** [comment]
Tests are super annoying here, we need to support older versions of the query that doesn't return runSpec. We can either catch that error like implemented here, or do introspection...

**Comment by gtarpenning** [comment]
One test should fail, on the manual pushToRunQueueByName, until the new backend path is in

**Comment by gtarpenning** [comment]
add mocked test

**Review by KyleGoyette — APPROVED** [review]

**Review by dmitryduev — APPROVED** [review]
👍🏻 Looks safe as far as I can tell!

**Pull request merged**
