### PR TITLE
security(deps): bump github.com/vektah/gqlparser/v2 from 2.5.11 to 2.5.16

### LINKED ISSUE #7818: [Q] Upgrade to gqlparser 2.5.14 in next release?
Hi there, 

Recently there's a security issue in the `vektah/gqlparser` open-source library, which you are currently using in your [core code](https://github.com/wandb/wandb/blob/main/core/go.mod) "`github.com/vektah/gqlparser/v2 v2.5.11 // indirect`". According to GitHub security advisory [GHSA-2hmf-46v7-v6fx](https://github.com/advisories/GHSA-2hmf-46v7-v6fx), this issue allows a remote attacker to cause a denial of service.

We're using Wandb in our project and due to security requirements we have to resolve any security issue which is filed as GitHub security advisory. And, to resolve this issue and enhance the security of wandb, I wondered if it's possible for you to upgrade `gqlparser `to version 2.5.14, where this vulnerability has been addressed, in your next release version.

Thank you!

### PR DESCRIPTION
**Pull request by wandb-kc**
Description
-----------
- Fixes #7818

What does the PR do? Include a concise description of the PR contents.

Upgrades `github.com/vektah/gqlparser/v2` from 2.5.11 to 2.5.16 to address a remote DoS vulnerability

- [x] I updated CHANGELOG.md, or it's not applicable

Testing
-------
How was this PR tested?

### CODE REVIEW

**Review by kptkin — APPROVED** [review]
Thanks for the fix

**Comment by kptkin** [comment]
> Thank you for making the changes to address my concern! Will this be included in the next release wandb 0.17.3?

Thanks for reporting the issue. Helping us stay secure :) 

Yes it will be included in the upcoming release. We do most of our releases out of the main branch, so once a PR is merged it will usually be included in the next release.

**Comment by Veronicacz** [comment]
> > Thank you for making the changes to address my concern! Will this be included in the next release wandb 0.17.3?
> 
> Thanks for reporting the issue. Helping us stay secure :)
> 
> Yes it will be included in the upcoming release. We do most of our releases out of the main branch, so once a PR is merged it will usually be included in the next release.

Thank you for your prompt action to keep the client secure :) 
Just out of curiosity, how often do you release new versions? I noticed that version 0.17.2 was released yesterday and am wondering when the next release is scheduled.

**Comment by kptkin** [comment]
> > > Thank you for making the changes to address my concern! Will this be included in the next release wandb 0.17.3?
> > 
> > 
> > Thanks for reporting the issue. Helping us stay secure :)
> > Yes it will be included in the upcoming release. We do most of our releases out of the main branch, so once a PR is merged it will usually be included in the next release.
> 
> Thank you for your prompt action to keep the client secure :) Just out of curiosity, how often do you release new versions? I noticed that version 0.17.2 was released yesterday and am wondering when the next release is scheduled.

We have a dedicated release once a month, first week of every month, but for critical issues, we do out of schedule releases, so in this case we will probably try to target to release as soon as possible.

**Pull request merged**
